use std::marker::PhantomData;

use crate::{
    CallError, NotifyError,
    frame::rpc_request::{RpcRequestBuilder, RpcRequestBuilderUninit},
    send_request::SendRequest,
};

/// A typed, generated RPC request that can be executed or sent as a notification.
///
/// Values of this type are returned by stubs generated by [`crate::service`].
/// They are single-use: consuming the value when [`Self::call`] or [`Self::notify`]
/// sends the request.
///
/// # Example
/// ```rust
/// use std::{sync::Arc, marker::PhantomData};
///
/// #[rpc_genie::service]
/// mod service {
///     pub struct Server<Stream> {}
///
///     impl<Stream> Server<Stream> {
///         #[remote_method]
///         pub fn foo() {}
///     }
///
///     pub struct Client<Stream> {}
/// }
///
/// const MAX_FRAME_SIZE: usize = 1024 * 1024;
///
/// #[tokio::main]
/// async fn main() {
///     let Ok(client_handle) = rpc_genie::tcp::connect_client(
///         "127.0.0.1:12345",
///         MAX_FRAME_SIZE,
///         Arc::new(service::Client {
///             _stream: PhantomData
///         })
///     ).await else {
///         return;
///     };
///
///     // You get a SingleRequestSender whenever you call a remote method.
///     let request_sender: rpc_genie::SingleRequestSender<_, _> = client_handle.server_stub.foo();
///     request_sender.notify().await.unwrap();
/// }
/// ```
pub struct SingleRequestSender<RequestSender, ResponseType> {
    request_sender: RequestSender,
    request_builder: RpcRequestBuilder<RpcRequestBuilderUninit, String>,
    _response_type: PhantomData<fn() -> ResponseType>,
}

impl<RequestSender, ResponseType> SingleRequestSender<RequestSender, ResponseType>
where
    RequestSender: SendRequest,
    ResponseType: serde::de::DeserializeOwned,
{
    #[doc(hidden)]
    pub fn new(
        request_sender: RequestSender,
        request_builder: RpcRequestBuilder<RpcRequestBuilderUninit, String>,
    ) -> Self {
        Self {
            request_sender,
            request_builder,
            _response_type: PhantomData,
        }
    }

    /// Send the request and wait for the response.
    pub async fn call(self) -> Result<ResponseType, CallError> {
        self.request_sender
            .call(self.request_builder)
            .await?
            .get_response()
            .map_err(Into::into)
    }

    /// Send the request without waiting for a response.
    pub async fn notify(self) -> Result<(), NotifyError> {
        self.request_sender.notify(self.request_builder).await
    }
}
